Add option parser

diff --git a/scripts/worker/slurm/jobscript.tmpl b/scripts/worker/slurm/jobscript.tmpl
--- a/scripts/worker/slurm/jobscript.tmpl
+++ b/scripts/worker/slurm/jobscript.tmpl
@@ -1,29 +1,57 @@
-#!/usr/bin/env bash
-#SBATCH -A lpt2_sysadmin
-#SBATCH --cluster=wice
-#SBATCH --nodes=1 --cpus-per-task=1 
-#SBATCH hetjob
-#SBATCH --nodes=2 --ntasks=36 --cpus-per-task=4
-#SBATCH --time=00:15:00
+{shebang}
+{scheduler_directives}
+#
+# variables that should be subsituted
+#   * shebang, shebang for this script ({shebang})
+#   * scheduler_directives
+#   * worker_path ({worker_path})
+#   * server_info ({server_info})
+#   * server_log_opt, e.g., --log path_to_log_file ({server_log_opt})
+#   * port_opt, e.g., --port 1234 ({port_opt})
+#   * server_start_delay, 5 (in seconds) ({server_start_delay})
+#   * workfile ({workfile})
+#   * client_log_prefix_opt, e.g., --log_prefix client_log_prefix ({client_log_prefix_opt})
+#   * env_var_exprs, e.g., '^VSC' '^PBS_' ({env_var_exprs})
+#   * num_cores ({num_cores})
+#   * exit_on_client_fail, i.e., true or false ({exit_on_client_fail})
+#
 
-source setup_wice.sh
-work_file=examples/omp_workload.txt
-server_info=slurm_server_info.txt
+# source worker software environment variables (LD_LIBRARY_PATH et al.)
+source "{worker_path}/conf/worker_env.sh"
 
-# (>&2 echo "launching server...")
+# source worker functions used in this script
+source "{worker_path}/scripts/worker_functions.sh"
+
+# file to store the server details
+SERVER_INFO={server_info}
+
+# start the server
 srun --exclusive --nodes=1 --ntasks=1 --cpus-per-task=1 \
+    "{worker_path}/bin/worker_server" \
+        {server_log_opt} \
+        {port_opt} \
+        --workfile "{workfile}" \
+        --server_info "{server_info}" &
+server_exit=$?
+if [ $server_exit -ne 0 ]
+then
+
+    (>&2 echo "### error: failed to launch server")
+    exit $server_exit
+fi
+
+# ensure it is up and running
+sleep {server_start_delay}
+
+# determine the server address and UUID for the clients to use
+uuid=$(cut -d ' ' -f 1 $SERVER_INFO)
+server=$(cut -d ' ' -f 2 $SERVER_INFO)
+
+(>&2 echo "### info: server launhed at '$server' with UUID '$uuid'")
      distr_wice/bin/worker_server \
         --workfile "$work_file" \
         --server_info $server_info &
 
-if [ $? -ne 0 ]
-then
-    (>&2 echo "### error: failed to launch server")
-    exit 1
-fi
-sleep 5
-uuid=$(cut -d ' ' -f 1 $server_info)
-server=$(cut -d ' ' -f 2 $server_info)
 
 export OMP_PROC_BIND=true
 export OMP_PLACES=cores
@@ -33,12 +61,21 @@ do
     srun --exclusive --het-group=1 \
         --ntasks=1 --nodes=1 --cpus-per-task=$SLURM_CPUS_PER_TASK_HET_GROUP_1 \
         --threads-per-core=1 \
-            distr_wice/bin/worker_client \
-                --server $server --uuid $uuid &
-    if [ $? -ne 0 ]
+            "{worker_path}/bin/worker_client" \
+                --server "$server" --uuid "$uuid" {client_log_prefix_opt} \
+                $numactl_opt --host_info "$host_info" &
+    client_exit=$?
+    if [ $client_exit -eq 0 ]
     then
-        (>&2 echo "### error: client $client_id failed to launch")
+        (>&2 echo "### info: client launhed on '${{client_nodes[0]}}'")
+    else
+        (>&2 echo "### error: client failed to launhed on '${{client_nodes[0]}}', exit status $client_exit")
+        if [ {exit_on_client_fail} ]
+        then
+            exit $client_exit
+        fi
     fi
 done
 
+# wait for the server to finish
 wait
