Fix jobscript template

diff --git a/scripts/worker/pbs_torque/jobscript.tmpl b/scripts/worker/pbs_torque/jobscript.tmpl
--- a/scripts/worker/pbs_torque/jobscript.tmpl
+++ b/scripts/worker/pbs_torque/jobscript.tmpl
@@ -1,19 +1,20 @@
 {shebang}
+{scheduler_directives}
 #
 # variables that should be subsituted
-#   * shebang, shebang for this script
+#   * shebang, shebang for this script ({shebang})
 #   * scheduler_directives
-#   * worker_path
-#   * server_info
-#   * log_opt, e.g., --log path_to_log_file
-#   * {port_opt}, e.g., --port 1234
-#   * server_start_delay, 5 (in seconds)
-#   * workfile
-#   * env_var_exprs, e.g., '^VSC' '^PBS_'
-#   * num_cores
-#   * exit_on_client_fail, i.e., true or false
+#   * worker_path ({worker_path})
+#   * server_info ({server_info})
+#   * server_log_opt, e.g., --log path_to_log_file ({server_log_opt})
+#   * port_opt, e.g., --port 1234 ({port_opt})
+#   * server_start_delay, 5 (in seconds) ({server_start_delay})
+#   * workfile ({workfile})
+#   * client_log_prefix_opt, e.g., --log_prefix client_log_prefix ({client_log_prefix_opt})
+#   * env_var_exprs, e.g., '^VSC' '^PBS_' ({env_var_exprs})
+#   * num_cores ({num_cores})
+#   * exit_on_client_fail, i.e., true or false ({exit_on_client_fail})
 #
-{scheduler_directives}
 
 # source worker software environment variables (LD_LIBRARY_PATH et al.)
 source "{worker_path}/conf/worker_env.sh"
@@ -26,7 +27,7 @@ SERVER_INFO={server_info}
 
 # start the server
 "{worker_path}/bin/worker_server" \
-    {log_opt} \
+    {server_log_opt} \
     {port_opt} \
     --workfile "{workfile}" \
     --server_info "{server_info}" &
@@ -47,12 +48,15 @@ server=$(cut -d ' ' -f 2 $SERVER_INFO)
 
 (>&2 echo "### info: server launhed at '$server' with UUID '$uuid'")
 
+# determine log directory
+
+
 # environment variables will not be available on non-server nodes,
 # so they need to be passed to the client explicitly
 env_variables=$(compute_env_vars {env_var_exprs})
 
 # launch clients
-nodes=$(cat $PBS_NODEFILE)
+nodes=($(cat $PBS_NODEFILE))
 if [ -z "$num_cores" ]
 then
     num_cores=1
@@ -72,15 +76,18 @@ do
     then
         numactl_opt="--numactl ${{numactl_args[$client_num]}}"
     fi
-    ssh ${{client_nodes[0]}} "{worker_path}/bin/worker_client" \
-        --server "$server" --uuid "$uuid" \
-        $env_variables $numactl_opt --host_info "$host_info" &
+    ssh ${{client_nodes[0]}} << EOF
+        source "{worker_path}/conf/worker_env.sh";
+        nohup "{worker_path}/bin/worker_client" \
+            --server "$server" --uuid "$uuid" {client_log_prefix_opt} \
+            $env_variables $numactl_opt --host_info "$host_info" >> nohup.txt &
+EOF
     client_exit=$?
     if [ $client_exit -eq 0 ]
     then
-        (>&2 echo "### info: client launhed on '$client_node'")
+        (>&2 echo "### info: client launhed on '${{client_nodes[0]}}'")
     else
-        (>&2 echo "### error: client failed to launhed on '$client_node', exit status $client_exit")
+        (>&2 echo "### error: client failed to launhed on '${{client_nodes[0]}}', exit status $client_exit")
         if [ {exit_on_client_fail} ]
         then
             exit $client_exit
